title: Huang Kangjie's Homepage
page-top-title: Huang Kangjie
top-section-bg-text: Computer Science
home-subtitle: Huang Kangjie&ensp;|&ensp;黄康杰
copyright-text: '&copy; Huang Kangjie 2023-2025. All Rights Reserved.'
